name: Build and Deploy

on:
  push:
    branches: [main]
    paths: [ 'src/**' ]
  pull_request:
   branches: [ '*' ]
  workflow_dispatch:

env:
  REGISTRY: ${{ vars.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io
  IMAGE_NAME: simplestore
  APP_NAME: ${{ vars.AZURE_APP_SERVICE_NAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure
          uses: azure/login@v2
          with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Log in to ACR
        run: az acr login --name ${{ vars.ACR_NAME }}

      - name: Build and push container image
        run: |
          IMAGE_TAG=${{ vars.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker build -t "$IMAGE_TAG" ./src
          docker push "$IMAGE_TAG"

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.APP_SERVICE_NAME }}
          images: ${{ vars.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
